### ISSUE TITLE
Sweep to the same address to reduce the number of UTXOs

### ISSUE THREAD

**Issue by polarker** [alephium/alephium-wallet#101]
If the user wants to make a large tx using many UTXOs, the tx cannot be built due the limits on tx inputs and gas. We'd suggest users to merge the existing UTXO with `sweep-address` endpiont.

**Comment by polarker** [comment]
@mvaivre This is high priority. Please consider to support this with high priority. It will be later if more users have this issue. I already got 2.

As we are discussed, we will use `UTXO consolidation` for the naming

**Comment by polarker** [comment]
How should this high priority be reflected in your project management?

**Comment by nop33** [comment]
I'll start working on this tmr and treat it as highest priority

**Comment by mvaivre** [comment]
Yes, we're on it, it was discussed yesterday  [here](https://alephium.slack.com/archives/C026MHDJD2N/p1641559534009700?thread_ts=1641559534.009700&cid=C026MHDJD2N)

**Comment by nop33** [comment]
@polarker @mvaivre I guess we can close this one now that the feature is implemented, correct?

**Comment by polarker** [comment]
LGTM
