### ISSUE TITLE
Display expected fee by calling an endpoint using the unsignedTx

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-wallet#112]
@polarker could you please provide some more info? Don't worry though, I'll have a look and figure it out on Swagger next week.

**Comment by tdroxler** [comment]
when you `/build` your transaction, you receive an `unsignedTx` as an hex string. You can then call the `/decode` endpoint to get a readable format of the `unsignedTx`. In that readable format you can find the fees that were automatically computed.

**Comment by polarker** [comment]
@tdroxler the `/decode` endpoint is very expensive. It should be better to return `gasAmount&gasPrice` in the response of `/build`

**Comment by tdroxler** [comment]
good idea, we could also return more info if needed, maybe even the full data which is returned by the `decode`. Since we `encode` it just before responding: https://github.com/alephium/dev-alephium/blob/2bbb499295b652c1dcb91691a70017d354e80d28/api/src/main/scala/org/alephium/api/model/BuildTransactionResult.scala#L37

**Comment by polarker** [comment]
Let's don't add too many fields for now to keep the response as lightweight as possible. It's always easier to add new fields than to remove fields

**Comment by nop33** [comment]
@tdroxler / @polarker let me know when the endpoint will be updated so I can start working on this, thanks!

**Comment by polarker** [comment]
@tdroxler please help me on this task: https://github.com/alephium/alephium/issues/500

**Comment by polarker** [comment]
@nop33 API is updated. In `BuildTransactionResult`, there are `gasAmount` and `gasPrice` now. I will try to release `1.2.5` by the end of this week

**Comment by nop33** [comment]
This has already been implemented by https://github.com/alephium/alephium-wallet/pull/128

Closing issue
