### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by Hammerkem** [alephium/alephium-wallet#113]
Создание майнинг кошелька возможно ?

**Comment by nop33** [comment]
You will get better support from the community on our Discord! We have a wallet dedicated channel, as well as a Russian one!

https://discord.gg/c2dRf6mV

To quickly answer your question: the desktop wallet generates an address in a random group at the moment. To create a mining wallet and mine solo (not joining in a mining pool), you need one address in each group. So it is recommended to do it through the Swagger interface of the full node.

If you want to join a mining pool, creating a wallet through the desktop wallet should be sufficient.
