### ISSUE TITLE
ARM64 support on Linux

### ISSUE THREAD

**Issue by blackmennewstyle** [alephium/alephium-wallet#115]
Hello talented devs :)

Can we hope for some arm64 support in the future? I'm planning to install the wallet on a Raspberry Pi 4 8GB running GNU/Linux Debian 11 - kernel 5.10.0-9-arm64, is it possible at the current stage of the project? If not, will it be possible in the future? :$

**Comment by mvaivre** [comment]
Hey there, thanks for your message!
The ARM64 architecture is not yet supported on Linux, mostly due to the lack of demand so far. But here you are... 
So yeah, we can definitely hope for some arm64 in the future, probably in the next release! ;)

**Comment by blackmennewstyle** [comment]
> Hey there, thanks for your message! The ARM64 architecture is not yet supported on Linux, mostly due to the lack of demand so far. But here you are... So yeah, we can definitely hope for some arm64 in the future, probably in the next release! ;)

Nice :)
Merci beaucoup Mikaël !
Enjoy your week :)

**Comment by mvaivre** [comment]
@nop33 Hey Ilias, could you look into this while I'm testing the address derivation & UX?
It should basically be [1 flag to add](https://www.electron.build/cli.html) in the package.json script + adapt the corresponding github build action.
Do you still have VMWare running on your M1 mac? If so, should be quite easy to spin up an arm64 build of debian / ubuntu. If not, don't spend to much effort on this RN. KMP, thanks!

**Comment by nop33** [comment]
Hey @mvaivre, I am working on implementing tests for the settings utility functions of the wallet project, as we discussed in the PR. I don't have a VMWare installed, but I can install one. I can do that after I implement the tests.

**Comment by nop33** [comment]
Hello @blackmennewstyle! I've added a new npm script that you can use to build the app for ARM64 from source (I updated the README with instructions). Unfortunately, I couldn't get GitHub's CI to work with ARM64 just yet. The process to build for ARM64 from source is very simple:
```
npm install
npm run electron-pack-linux:arm64
```

Keep in mind that the `master` branch is cutting-edge code and should not be used in production. Use code from the releases instead.

**Comment by blackmennewstyle** [comment]
> Hello @blackmennewstyle! I've added a new npm script that you can use to build the app for ARM64 from source (I updated the README with instructions). Unfortunately, I couldn't get GitHub's CI to work with ARM64 just yet. The process to build for ARM64 from source is very simple:
> 
> ```
> npm install
> npm run electron-pack-linux:arm64
> ```
> 
> Keep in mind that the `master` branch is cutting-edge code and should not be used in production. Use code from the releases instead.

Hello :)

Thank you for your response. I'm not really an expert with npm but if i understand correctly, i need to download the sources from a release, for example: https://github.com/alephium/alephium-wallet/archive/refs/tags/v1.1.0.tar.gz . And i should replace the `package.json` contained in the tar.gz file with this one: https://github.com/alephium/alephium-wallet/blob/support-arm64-linux/package.json

**Comment by nop33** [comment]
> ..., i need to download the sources from a release, for example: https://github.com/alephium/alephium-wallet/archive/refs/tags/v1.1.0.tar.gz . And i should replace the package.json contained in the tar.gz file with this one: https://github.com/alephium/alephium-wallet/blob/support-arm64-linux/package.json

That would probably work, but there might have been other changes in the `package.json` file between `v1.1.0` and the latest `master` which might cause your procedure to not work. I would recommend following the following procedure (assuming you are not very familiar with `git`):

1. Extract the contents of the ZIP/tar.gz file
2. Open your terminal
3. Navigate to the extracted ZIP folder
4. Execute the command `npm install`
5. Execute the command `npm run build && npx electron-builder -l --arm64`
6. The `.deb` file will be inside the `/dist` directory

I hope this helps!

**Comment by nop33** [comment]
Hm, I didn't face this issue on my arm64 MacBook. Maybe this helps? https://github.com/jordansissel/fpm/issues/1801#issuecomment-919877499

**Comment by blackmennewstyle** [comment]
> 



> Hm, I didn't face this issue on my arm64 MacBook. Maybe this helps? [jordansissel/fpm#1801 (comment)](https://github.com/jordansissel/fpm/issues/1801#issuecomment-919877499)

Oh i actually remember using that command with `yarn` for building LBry for my Raspberry Pi 4, i should have thought about it :)
```
export USE_SYSTEM_FPM=true
npm run build && npx electron-builder -l --arm64

> alephium-wallet@1.0.2 build
> cross-env REACT_APP_VERSION=$npm_package_version INLINE_RUNTIME_CHUNK=false REACT_APP_CSP="script-src 'self'" react-scripts build

Creating an optimized production build...
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.2

Please only submit bug reports when using the officially supported version.

=============
Compiled successfully.

File sizes after gzip:

  783.3 KB (-27 B)  build/static/js/2.e5b24d0c.chunk.js
  180.75 KB (-4 B)  build/static/js/main.342dd536.chunk.js
  2.57 KB (-44 B)   build/static/css/2.7983be9c.chunk.css
  781 B             build/static/js/runtime-main.d77c4cef.js
  432 B             build/static/css/main.a4d683a3.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

  \u2022 electron-builder  version=22.14.5 os=5.10.0-11-arm64
  \u2022 loaded configuration  file=package.json ("build" field)
  \u2022 loaded parent configuration  preset=react-cra
  \u2022 writing effective config  file=dist/builder-effective-config.yaml
  \u2022 packaging       platform=linux arch=arm64 electron=15.3.2 appOutDir=dist/linux-arm64-unpacked
  \u2022 building        target=AppImage arch=arm64 file=dist/Alephium-1.0.2-arm64.AppImage
  \u2022 building        target=deb arch=arm64 file=dist/alephium-wallet_1.0.2_arm64.deb
```
Definitely made the trick. Successfully built and installed :)
With root privileges
```
dpkg -i dist/alephium-wallet_1.0.2_arm64.deb 
Selecting previously unselected package alephium-wallet.
(Reading database ... 242126 files and directories currently installed.)
Preparing to unpack .../alephium-wallet_1.0.2_arm64.deb ...
Unpacking alephium-wallet (1.0.2) ...
Setting up alephium-wallet (1.0.2) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```
![Screenshot_2022-03-01_15-03-48](https://user-images.githubusercontent.com/4682874/156193460-efacdddc-6103-4780-a39c-cf98a4d8e0c9.png)
Thank you so much for your assistance :)
