### ISSUE TITLE
Find a clearer way to display amounts

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-wallet#116]
I had this discussion with @mvaivre the other day:

Something that has been bugging me a lot and I see other people having the same issue: I find it hard to distinguish the abrreviated amounts.
1.000K ℵ
1.123 ℵ
1.002K ℵ
1.002 ℵ
It all looks too similar, especially when they are aligned on the right, as it is the case in the wallet (and also explorer).

Using 3 decimal points is triggering the "thousands" pattern in my brain and I always think (in the example above) that 1.002 ℵ is 1 thousand and 2 ℵ.

![image](https://user-images.githubusercontent.com/1579899/149897626-ef9e633b-2a6e-4d3b-bf6c-dcd7e1b25b85.png)

Things we could test out:
1. Show only 1 or 2 decimals when using K, M etc, so that the above would be 8.6K ℵ or 8.68K ℵ
2. Abbreviate the 0s in general when they are not needed so that the above becomes 1 ℵ
3. Showing only 2 decimals instead of 3, which is a much more common pattern when talking about currencies (cents), unless the amount is less than 0.01 (like consolidation transaction fees), in which case we display the full precision (or just 3 decimals, like now).
4. Do not use the letter K so the above becomes 8681.23 ℵ (or even better, 8'681.23 ℵ), and only start using M and B when we surpass a million.

I personally like the combination of options 3 and 4.

**Comment by polarker** [comment]
How does Metamask do it?

**Comment by nop33** [comment]
| Metamask | BRD | Argent |
| ---------- | -----| -------|
| Metamask seems to display full precision, abbreviating unnecessary 0s, with no decimals when not needed. I don't know how to test to see how they display values > 999 and > 999999. | Bread wallet seems to be using full precision. I also don't know how to test large amounts. | Argent seems to use max 4 decimals, abbreviating 0s when possible and not using the "K" letter to signify thousands (but a "," instead, which I find confusing) |
| ![image](https://user-images.githubusercontent.com/1579899/149902212-f000e8c9-1741-499d-a0d0-63386aaee4a5.png) | ![image](https://user-images.githubusercontent.com/1579899/149903330-ce39acd4-b541-4286-ab41-13c18c11d97a.png) | ![image](https://user-images.githubusercontent.com/1579899/149902873-ca7b1482-31bd-4ace-8cb2-c0393abb7bcf.png) |

**Comment by mvaivre** [comment]
Thanks for summarising the discussion in this Issue @nop33.

I'm also in favour of:

- Showing 2 decimals by default for numbers >= 1.00
- Showing more decimals for small amounts (3 or full precision, design choice depending on where it is in the UI.)
- Not using the letter for thousands, starting only with M.
- Adding a separator for better readability (15'430.00). Let's not use a comas, which I find confusing.

Metamask still struggles with big amounts, less advanced than us: https://github.com/MetaMask/metamask-extension/issues/5558

**Comment by polarker** [comment]
I have a simpler proposal: we keep 5 numbers always, which means the error is always less than `0.1%`. We could remove the ending zeros, or keep the ending zeros.

In this format, the following are valid: `2.1024, 21.024, 210.24K, 2.1024K, 21.024K`.

How do you think?

**Comment by nop33** [comment]
What do you mean _"the error is always less than 0.1%."_? Which error?

I personally don't like it so much with always displaying 5 decimals (see screenshot). I like it much more with 2. However, I would still remove the trailing "0"s when they are not needed.

| 5 decimals | 2 decimals |
| ----------- | ---------- |
| ![image](https://user-images.githubusercontent.com/1579899/149964907-f1284b95-ae7e-4658-ab19-652aa37a7fc8.png) | ![image](https://user-images.githubusercontent.com/1579899/149965109-8f8372e8-4d31-4152-a8e8-f6a6cce0840d.png) ![image](https://user-images.githubusercontent.com/1579899/149968410-7b17598b-d62d-43b4-8592-490bf75cf83f.png) ![image](https://user-images.githubusercontent.com/1579899/149968481-9d2ac0da-388b-4363-ba18-c74d5547c1f4.png) |

**Comment by nop33** [comment]
I think this is already a great improvement:

- 5 decimals for small values (< 1 ALPH)
- Rounding to 2 decimals when > 1 ALPH
- No decimals when the amount is an integer

![image](https://user-images.githubusercontent.com/1579899/149971193-db07e078-b4f7-437f-8e51-c81db0660a9c.png)

![image](https://user-images.githubusercontent.com/1579899/149971317-4c35e829-fc8c-4191-8308-2c9fd808fa82.png)

**Comment by mvaivre** [comment]
I think @polarker was saying 5 numbers in total (including the decimals), not 5 decimals.

But IMO this doesn't help readability, as it's hard to distinguish quickly if some amounts are bigger than others. If we take the example above and stack the numbers:

| 5 numbers | Option discussed before |
| --- | --- |
| 2.1024 | 2.10 |
21.024 | 21.02 |
2.1024K | 2'102.40 |
21.024K | 21'024 |
210.24K | 210'240 |

The second option really helps distinguishing orders of magnitude in a glance.

@nop33 Looking at the example above, I'm not 100% sure we should remove decimals for integers. I'm like - 80% sure.

**Comment by nop33** [comment]
Check the images again, I updated the instead of making a new comment to spam less, but in retrospect I should have done a new comment I guess 😅 

> I think @polarker was saying 5 numbers in total (including the decimals), not 5 decimals.

Ah! Misunderstood.

> The second option really helps distinguishing orders of magnitude in a glance.

Agreed.

> Looking at the example above, I'm not 100% sure we should remove decimals for integers. I'm like - 80% sure.

I personally like it, it's very clean and straightforward.

**Comment by nop33** [comment]
Adding two 0s as decimals in integers, it would look like this. Also nice.

![image](https://user-images.githubusercontent.com/1579899/149975804-a63ce227-9348-4db4-a96d-6aebfd5de095.png)

![image](https://user-images.githubusercontent.com/1579899/149975668-fc421590-8ece-4766-a312-c4b82ad5dbb1.png)

**Comment by chloekek** [comment]
Some wallets show decimals in smaller font. This very clearly distinguishes them from digits in the integer part.

**Comment by mvaivre** [comment]
> Some wallets show decimals in smaller font. This very clearly distinguishes them from digits in the integer part.

That could be interesting, and may be worth a quick experiment. 
Note: we would keep a regular size if the amount is < 1. 
WDYT @nop33 ?

**Comment by nop33** [comment]
I think it will not look good, but I can experiment with it tmr!

**Comment by mvaivre** [comment]
> I think it will not look good, but I can experiment with it tmr!

Rather than playing with the `font-size` we could reduce the `opacity` a bit, which would probably look better as we conserve the layout alignements.

**Comment by polarker** [comment]
Update, with 5 numbers (not decimals), the error is less than `0.01%` always.

**Comment by polarker** [comment]
We need to consider both precision and user experience. For precision we need to set an upper bound for errors. `0.01%` might be a nice one. For better user experience, we might not want to show too many digits, so 5 or 6 numbers is good.

**Comment by nop33** [comment]
Considering both precision and UX, I think the solution below covers everything:

- Amounts <= 0.001 are rounded up to the 5th decimal point, to cover cases like #110
- Amounts > 0.001 and < 0.01 are rounded up to the 3rd decimal point, to show a meaningful amount in cases of small gas fees like for consolidation transactions
- Amounts >= 0.01 and < 1'000'000 are rounded to the 2nd decimal point and do not use abbreviation with letter "K" to signify "thousands"
- Apostrophe is added for amounts >= 1'000 and < 1'000'000
- Amounts >= 1'000'000 are still displayed with a letter suffix [M|B|T] and there is no apostrophe
- Font size for decimal points is reduced to `0.85em`

![image](https://user-images.githubusercontent.com/1579899/150087046-2b411814-1211-40d6-b159-4b0e8944b9ee.png)

**Comment by mvaivre** [comment]
LGTM! I'm not sure about the font-size change though - as discussed, let's not touch the digit's styling for now, I'll continue iterating in my mockups. 
Regarding your comments @polarker, for now the 100% precise amounts can be consulted with just one click in the explorer. In an upcoming iteration (working on mockups now), the precise data will be directly displayed in a dedicated panel in the wallet. A good mix between readability and precision.

**Comment by polarker** [comment]
LGTM!

**Comment by nop33** [comment]
Closing issue since https://github.com/alephium/alephium-wallet/pull/117 was merged
