### ISSUE TITLE
How to reset my password in Alephium wallet?

### ISSUE THREAD

**Issue by BBFLYMINING** [alephium/alephium-wallet#122]
I use the same password today at 11am (Singapore time zone) but the wallet keep reject me saying invalid password. May i know any method to reset the password?

**Comment by polarker** [comment]
> I use the same password today at 11am (Singapore time zone) but the wallet keep reject me saying invalid password. May i know any method to reset the password?

It must be that you mistyped when you create the wallet. You will have to restore the wallet with your 24 mnemonic words.
