### ISSUE TITLE
Mining balance

### ISSUE THREAD

**Issue by MrAllusive** [alephium/alephium-wallet#123]
Hello! I was curious, I have been mining for 6 1/2 hours and the balance in your wallet still shows 0. I was wondering is there a minimum threshold? Thanks

**Comment by nop33** [comment]
Hello @MrAllusive! There's no threshold, the full precision of the address holding's should be shown if you press the "refresh" button on the top right. You can also check your addresses in the [explorer](http://explorer.alephium.org/).

**Comment by MrAllusive** [comment]
I was able to figure it out. Thanks so much for your help!
