### ISSUE TITLE
Wallet Password Issue

### ISSUE THREAD

**Issue by Biolite80** [alephium/alephium-wallet#126]
This is the second time i have had a wallet password tell me its icorrect despite me knowing its correct. I know how much should be there please help

**Comment by nop33** [comment]
Hello @Biolite80. You can restore your wallet using your 24 words and create a new password.

For the record, when you say _"This is the second time i have had a wallet password tell me its incorrect"_ you mean an Alephium wallet in both cases?

Similar issue: https://github.com/alephium/alephium-wallet/issues/122

**Comment by Biolite80** [comment]
Yes the Alephium wallet on official website

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 14, 2022 at 2:59 AM, Ilias ***@***.***> wrote:   


Hello @Biolite80. You can restore your wallet using your 24 words and create a new password.

For the record, when you say "This is the second time i have had a wallet password tell me its incorrect" you mean an Alephium wallet in both cases?

Similar issue: #122

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nop33** [comment]
I am afraid I cannot reproduce your issue. Please, restore your wallet with the 24 words to reset the password.

**Comment by Biolite80** [comment]
How? I cannot find a restore option in the wallet at all.

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 16, 2022 at 2:48 AM, Ilias ***@***.***> wrote:   


I am afraid I cannot reproduce your issue. Please, restore your wallet with the 24 words to reset the password.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nop33** [comment]
![image](https://user-images.githubusercontent.com/1579899/154236937-e721745b-3334-4873-b44d-ba42b324f78e.png)

![image](https://user-images.githubusercontent.com/1579899/154237007-dbd50772-da66-44bd-ab72-a880c45f073d.png)

**Comment by Biolite80** [comment]
So I need to delete the account on their first correct?

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 16, 2022 at 4:39 AM, Ilias ***@***.***> wrote:   






—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nop33** [comment]
You don't NEED to, but since you cannot access it, it doesn't make sense to keep it. The most important thing is to have your 24 words. By the way, you should never reveal those words to anyone, not even support. :)

**Comment by Biolite80** [comment]
Thank you! All set back mining now

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 16, 2022 at 4:43 AM, Ilias ***@***.***> wrote:   


You don't NEED to, but since you cannot access it, it doesn't make sense to keep it. The most important thing is to have your 24 words. By the way, you should never reveal those words to anyone, not even support. :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
