### ISSUE TITLE
WALLET EMPTY BUT TRANSACTION ON EXPLORER

### ISSUE THREAD

**Issue by obigunshinobi** [alephium/alephium-wallet#127]
HI,

I HAVE TRIED EVERYTHING BUT I DON'T UNDERSTAND WHY THE WALLET SHOW NO COINS MEANWHILE I SHOULD HAVE RECEIVED ALREADY COINS AS SHOWN IN THE CHAIN EXPLORER
![image](https://user-images.githubusercontent.com/99685162/153929433-0cba3cdf-795e-4845-93ba-f1cbf931234c.png)
![image](https://user-images.githubusercontent.com/99685162/153929527-0f44692f-c843-4831-b7d6-6cd8cc1b0114.png)

**Comment by nop33** [comment]
Hey @obigunshinobi , I see that you are receiving some support on Discord. I'll go ahead and close this issue and monitor the Discord discussion to make sure you solve your issue.
