### ISSUE TITLE
Update informational links to new wiki content

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-wallet#139]
There is a number of links in the next version of the wallet that need to link to some wiki page, before we can release the new version. Maybe we could have a new _4.3 Desktop Wallet Guide_ page on the wiki.

Here's the list of links we need a page for:

### 1. Info link regarding 4 addresses in welcome page
We need some content to explain what this is (also appears in the following screenshot).

![image](https://user-images.githubusercontent.com/1579899/156404656-eb2675eb-40f5-47d8-ab0a-30c3fb11b010.png)

### 2. UTXO consolidation

We need to explain what UTXO consolidation is and why it is needed.

![image](https://user-images.githubusercontent.com/1579899/156405151-0090cbcc-e1a8-422f-b952-020cf6c8f7c5.png)

/cc @Sakrecoer @mvaivre

**Comment by Sakrecoer** [comment]
Note sure if i should assign myself, but i can make sure the pages exist, have the content needed and provide the URLs

**Comment by Sakrecoer** [comment]
I am currently on this. I just noticed this typo:
![image](https://user-images.githubusercontent.com/3484593/156742716-87d48a7b-a7c3-412e-be30-fcb1dbd44528.png)

Not sure how to file an issue about it as i don't really know where the content is located in the wallet and suspect you might have caught the typo already :)

**Comment by Sakrecoer** [comment]
Here is the first draft: https://github.com/alephium/wiki/commit/236c0f8a8f402f4b10b5a27f0f43c879b38d6d42

the URL for 1. will be: https://wiki.alephium.org/Desktop-Wallet-Guide.html#creating-a-mining-wallet-with-4-addresses
the URL for 2. will be: https://wiki.alephium.org/Desktop-Wallet-Guide.html#utxo-consolidation
