### ISSUE TITLE
Show a message when opening the wallet while offline

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-wallet#147]
As of today, the data is simply not loaded (no addresses, amounts etc.) but no error are shown.
Also, "refreshing" (using the dedicated header button) after getting back online doesn't work.

As a first step, when offline, we could show an error snackbar and replace the refresh icon with a "offline" icon.

In the future, we could cache previously loaded data to populate the UI, even when offline.

**Comment by lf94** [comment]
Should it be clear that the data presented is old?

**Comment by mvaivre** [comment]
Yes. An easy way could be to add a little state icon to the refresh button: 

![image](https://user-images.githubusercontent.com/6715943/157624495-b22cf5e2-9906-4a25-9c12-e37f47f12ae6.png)

With an explanation on hover: "(Not) Synchronized"
