### ISSUE TITLE
Scrolling changes the value of numeric input fields

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-wallet#165]
https://user-images.githubusercontent.com/1579899/158656267-222fb867-7993-4cb4-8512-5ce8701df603.mp4

**Comment by lf94** [comment]
Was this introduced between the old version and now? If not I'd leave it out of the milestone...

**Comment by lf94** [comment]
This is caused by `type='number'`. It's actually default browser behavior. A simple no-hack fix is to declare the input as `type='text'`.
