### ISSUE TITLE
Improve the help menu

### ISSUE THREAD

**Issue by 0xjac** [alephium/alephium-wallet#37]
The help menu is empty :disappointed: (see screenshot below)
It would be nice to have:
1. The wallet version
2. A "Report a bug" link which points to a new issue on this repo (i.e. https://github.com/alephium/alephium-wallet/issues/new) to let users easily provide feedback
3. Optionally a help/support link which points either to some documentation or to the discord chat

Also the "File" and especially the "Window" menus feel a bit useless and could be hidden.

![2021-10-30-033016_1916x1056_scrot](https://user-images.githubusercontent.com/2848217/139515877-5cb7675e-c865-42d5-99fc-f25e74215f9d.png)

> Note: This is inspired by the MyCrypto desktop wallet help menu

**Comment by mvaivre** [comment]
Thanks for your feedback. Good suggestions, we'll make sure to add them to our backlog!
