### ISSUE TITLE
Packing the extension is broken (because of zip)

### ISSUE THREAD

**Issue by 0xjac** [alephium/alephium-wallet#42]
Trying to build the extension with `npm run-script extension-pack` fails for me with: `sh: line 1: zip: command not found`.

<details><summary>full log</summary>

```shell
$ npm run-script extension-pack

> alephium-wallet@0.11.1 extension-pack
> rm alephium-wallet.zip; npm run-script extension-build && cd build && zip -r ../alephium-wallet.zip *


> alephium-wallet@0.11.1 extension-build
> rm -rf build; INLINE_RUNTIME_CHUNK=false npm run-script build;  cp public/background.js public/manifest.json build


> alephium-wallet@0.11.1 build
> cross-env REACT_APP_VERSION=$npm_package_version INLINE_RUNTIME_CHUNK=false react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  781.44 KB  build/static/js/2.dc6bb90c.chunk.js
  173.42 KB  build/static/js/main.84b8e747.chunk.js
  2.6 KB     build/static/css/2.05131dc2.chunk.css
  782 B      build/static/js/runtime-main.8cf0c569.js
  440 B      build/static/css/main.72438ba0.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

sh: line 1: zip: command not found
```

</details>

Looking at the npm run script:
```shell
rm alephium-wallet.zip; npm run-script extension-build && cd build && zip -r ../alephium-wallet.zip *
```
I think this is due to `zip` missing on my system.

I'd suggest switching from `zip` which can be missing on many systems, esp. Linux which uses `tar`/`bsdtar` by default to [`web-ext`](https://github.com/mozilla/web-ext) which is designed to build extensions.

Hopefully it is as straightforward as changing the above script to:
```shell
npm run-script extension-build && web-ext build --source-dir=build --artifacts-dir=. --filename=alephium-wallet.zip --overwrite-dest
```

and adding `web-ext` to `devDependencies` :wink: 

Let me know if you want a PR for it.

**Comment by polarker** [comment]
Hi Jacques @0xjac, many thanks for the issue report as well as the other issues.

It would be great if you could create a PR with your fix. I will add a Github action test after your PR

**Comment by 0xjac** [comment]
@polarker done in #43 I tested it and I can build the zip correctly and install it in Firefox as a temporary extension.

**Comment by polarker** [comment]
@0xjac I added a CI test for Linux, Windows and Macos in #44. Your fix works for all of the platform now.

Also added 500 ALPH bounty for your help :)
