### ISSUE TITLE
Show amount of locked tokens

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-wallet#50]
We could display information about part of the balance that is locked. 
Need some work on the backend @tdroxler  
To be refined.

**Comment by nop33** [comment]
@mvaivre 

Here are my 2 proposals.

| Text, no tooltip | Less text, tooltip when hovering |
| --------------- | -------------------------------|
| In this version we explain with a few words that a certain part of the total balance is locked. No need to explain any further with the use of a tooltip. | In this version we have a more minimal UI, but we might need to add some further explanation when hovering with the mouse over the locked amount and display it inside a tooltip. |
| <img width="1728" alt="Screenshot 2021-12-22 at 12 24 32" src="https://user-images.githubusercontent.com/1579899/147095956-ed0c9c8f-7f86-40e7-8a74-66bd971336fc.png"> | <img width="1728" alt="Screenshot 2021-12-22 at 13 52 58" src="https://user-images.githubusercontent.com/1579899/147095990-adbde5e7-b61c-47a3-8755-6cedf2312578.png">|

**Comment by mvaivre** [comment]
Def the second option IMO :)
