### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-wallet#60]
The mainnet launch is DONE and we've successfully delivered all needed features.
Now is the time for some UX polish ✨

We're focusing on removing little inconsistencies, clearing confusions and giving a bit more control through advanced features.

### New features

- [x] #57 
- [x] #19 
- [x] #23 
- [x] #87 
- [x] #50 
- [x] #35 

### Bugs

- [x] #53 
- [x] #54 
- [x] #48

**Comment by nop33** [comment]
Should we include a task _"Make use of alephium-js in explorer"_ or is this not part of the UX polish? It's more of code-UX I guess 😅

**Comment by mvaivre** [comment]
> Should we include a task _"Make use of alephium-js in explorer"_ or is this not part of the UX polish? It's more of code-UX I guess 😅

Yep, not a UX task. This will be a standalone "epic" I believe :)
