### ISSUE TITLE
When launching alephium wallet a second time on Windows, it offers option to import/start new wallet

### ISSUE THREAD

**Issue by diomark** [alephium/alephium-wallet#77]
I had alephium wallet running in the background and didn't realize it. launched alephium wallet again and it gave me the option to import/start new wallet.. might be confusing to some. (I almost re-imported my keys before realizing I had it running backgrounded in a different window).

It's basically launching a second instance instead of focusing on the already launched instance.

**Comment by nop33** [comment]
Hi @diomark, thanks for the feedback. Which version of Windows are you using?

When you say that the wallet was running in the background, do you mean that there was a window open and hidden behind other windows? Or that all windows of the application were closed and the process was still running in the background?

Was this the screen you saw when you opened the application the second time, after already creating a wallet?

![image](https://user-images.githubusercontent.com/1579899/145956240-a341bf73-6549-4966-9ad0-e428b88afc90.png)


Thanks a lot for the valuable feedback!

**Comment by polarker** [comment]
@nop33 @mvaivre  is this related to our latest fix PR? If so, we need to assign a bounty for this issue report

**Comment by nop33** [comment]
I haven't been able to reproduce this on my macbook, waiting for input from @diomark. I can check with @Arbaba who is using Windows, when I see him on Friday.

**Comment by diomark** [comment]
Windows 10 [Version 10.0.19043.1348]

The existing wallet window was just hiding behind other windows (i.e. functioning correctly/not crashed)

This is pretty easy to replicate -

Start alephium wallet, login

Start alephium wallet again (from start menu. It will give the options of new wallet or importing wallet (vs just focusing on the already opened wallet)

**Comment by diomark** [comment]
btw - yes - that's the screen that shows up when launching a second time. (option for new wallet or importing)

**Comment by nop33** [comment]
I managed to reproduce the issue. I still haven't found a solution. Some notes during my debugging: 

- We create new windows only when 2 events get triggered: `ready` and `activate`.
- Even when commenting out the callback of the `activate` event completely, when clicking the installed Windows Alephium app it still opens a second window. The only place where `createWindow` is now called is in the `ready` event callback. Updating the callback to the following snippet does not solve the problem (second window opens again):
  ```js
  app.on('ready', () => {
    if (mainWindow === null) createWindow()
  })
  ```
- I tried this, also no success:
  ```js
  app.on('ready', () => {
    if (BrowserWindow.getAllWindows().length) createWindow()
  })
  ```
- I tried updating the snippet to the following, again, without success:
  ```js
  app.whenReady().then(() => {
    if (mainWindow === null) createWindow()
  })
  ```
- It would seem that every time the installed `exe` is launched on Windows (located at `C:\Users\<my-user-name>\AppData\Local\Programs\alephium-wallet\Alephium.exe`), the `mainWindow` variable is set to `null`.

**Comment by polarker** [comment]
> I managed to reproduce the issue. I still haven't found a solution. Some notes during my debugging:
> 
> * We create new windows only when 2 events get triggered: `ready` and `activate`.
> * Even when commenting out the callback of the `activate` event completely, when clicking the installed Windows Alephium app it still opens a second window. The only place where `createWindow` is now called is in the `ready` event callback. Updating the callback to the following snippet does not solve the problem (second window opens again):
>   ```js
>   app.on('ready', () => {
>     if (mainWindow === null) createWindow()
>   })
>   ```
> * I tried this, also no success:
>   ```js
>   app.on('ready', () => {
>     if (BrowserWindow.getAllWindows().length) createWindow()
>   })
>   ```
> * I tried updating the snippet to the following, again, without success:
>   ```js
>   app.whenReady().then(() => {
>     if (mainWindow === null) createWindow()
>   })
>   ```
> * It would seem that every time the installed `exe` is launched on Windows (located at `C:\Users\<my-user-name>\AppData\Local\Programs\alephium-wallet\Alephium.exe`), the `mainWindow` variable is set to `null`.
> 
> Need to keep debugging...

Is this the same for Macos ?

**Comment by nop33** [comment]
> Is this the same for Macos ?

No. Everything works fine there.

**Comment by nop33** [comment]
It turns out that this is not a bug. This is the expected behavior on Windows. Here is an example with another popular electron app (Visual Studio Code). As you can see in the demo, double-clicking the executable opens a new window, exactly as it happens with our wallet.

https://user-images.githubusercontent.com/1579899/146947736-1f29af74-2252-4da1-a5a3-2e5bc50b95ac.mp4

**Comment by nop33** [comment]
However, if an account has already been created, the second window should display the Login page, not the new wallet creation/import page.

**Comment by nop33** [comment]
For the record, here's a demo of the problem:

https://user-images.githubusercontent.com/1579899/146949458-c8809220-a1de-4633-923b-78dc40011881.mp4
