### ISSUE TITLE
App is unresponsive when restarted with localhost services down (in dev mode)

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-wallet#79]
Steps to reproduce:
1. Start local services (node, miner, explorer-backend)
2. Run the wallet app and set the network settings to "Localhost"
3. Quit the app and all local services
4. Restart the app

Error:

```
api-alephium.js:106 GET http://localhost:12973/infos/self-clique net::ERR_CONNECTION_REFUSED
HttpClient.customFetch @ api-alephium.js:106

api-alephium.js:106  Uncaught (in promise) TypeError: Failed to fetch
    at CliqueClient.HttpClient.customFetch
```

**Comment by mvaivre** [comment]
Is it the case in the prod release (not only in dev mode)?

**Comment by nop33** [comment]
Nope, only dev mode, thankfully. I'm working on fixing this.
