### ISSUE TITLE
Slf4jLogger started

### ISSUE THREAD

**Issue by jonathanhatch** [alephium/alephium-wallet#86]
Do we need to be concerned about the full node running this logger? It seems to be a hot topic these days.

**Comment by tdroxler** [comment]
Slf4j isn't a logging library, it's a abstraction above which then allows to use any library. 

We are using logback as a logging library and it doesn't seem to suffer the same problem as log4j: http://slf4j.org/log4shell.html 
but reading that article I realize we should upgrade our logback to `1.2.8` (cc/ @polarker ).

**Comment by polarker** [comment]
> upgrade

We are not affected by log4shell. I checked that 1 day after it.

It's good to upgrade to `1.2.8` tho, due to possible vulnerability of logback

**Comment by jonathanhatch** [comment]
Brilliant. Thank you all for your diligence. I appreciate it.
